### ISSUE TITLE
What is your code work?

### ISSUE THREAD

**Issue by WZS519836505** [ilove-Moretz/RDGCN#1]
Hi, I'm new to the site and would like to ask what you are doing with your code?

**Comment by ilove-Moretz** [comment]
It is the source code of my paper.

**Comment by WZS519836505** [comment]
I am learning the code of RDGCN, what is the name of your paper?

**Comment by ilove-Moretz** [comment]
《A Residual Dynamic Graph Convolutional
Network for Multi-label Text Classification》NLPCC2021
