### ISSUE TITLE
could you please upload the data folder?

### ISSUE THREAD

**Issue by lincan1** [ilove-Moretz/RDGCN#2]
I'd like to test your model on the rcv1v2 dataset, but the '"../data/glove_word2id.json" file is not exsist.Would tou mind if you can send them to my e-mail account on canlin676@gmail.com. I really appreciate for your reply.

**Comment by ilove-Moretz** [comment]
> I'd like to test your model on the rcv1v2 dataset, but the '"../data/glove_word2id.json" file is not exsist.Would tou mind if you can send them to my e-mail account on [canlin676@gmail.com](mailto:canlin676@gmail.com). I really appreciate for your reply.

The file is too large to send by e-mail. I upload it to Google Driver. https://drive.google.com/file/d/1fw13Wgvu0LSaqk1PkYFQ5WxyEol5KlsW/view?usp=sharing
